



DELETE http://localhost:3003/api/blogs/5fb7de91ffa3f776e14e11ce


POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "deleteME",
    "author": "MeMyselfAndI",
    "url": "blogs.com/asshole",
    "likes": 2
}


PUT http://localhost:3003/api/blogs/5faaa9040a09973f6af10e43
Content-Type: application/json

{
    "likes": 4
}
