



PUT http://localhost:3001/api/blogs/5fbfc7273608cd8d44f691db
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbGRPcmFuZ2UiLCJpZCI6IjVmYjkzM2U1ZGQ1NWMyYmYxY2U4MWNjYSIsImlhdCI6MTYwNjQxOTE1MX0.ohAOZeMuNG__XfW43yaGdZgKjHtLsK1HlHhP9r-pkes 

  {
    "user": "5fb933e5dd55c2bf1ce81cca",
    "likes": 2,
    "author": "123",
    "title": "notiftest",
    "url": "adw"
  }